// Writes the `Fonts` module: one style object per bundled face, e.g. `Fonts.Inter.boldItalic`.
const fs = require("fs");
const path = require("path");
const { warnOnce } = require("./fonts");

const HEADER = "// Generated by expo-font-families.";

// Face names by CSS weight; italics add "Italic", except the regular one, which is just "italic".
const WEIGHT_NAMES = {
  100: "thin",
  200: "extraLight",
  300: "light",
  400: "regular",
  500: "medium",
  600: "semiBold",
  700: "bold",
  800: "extraBold",
  900: "black",
};

const faceKey = ({ weight, style }) => {
  if (style !== "italic") return WEIGHT_NAMES[weight];
  return weight === 400 ? "italic" : `${WEIGHT_NAMES[weight]}Italic`;
};

/** "Playfair Display" -> "PlayfairDisplay", "Source Sans 3" -> "SourceSans3". */
const familyKey = (family) => {
  const key = family
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join("");
  return /^[0-9]/.test(key) ? `_${key}` : key;
};

/** Source of the `Fonts` module for `plan`, as TypeScript or plain JavaScript. */
function fontsModule(plan, { typescript }) {
  const seen = new Map();
  const families = plan.families.map((family) => {
    const key = familyKey(family.family);
    if (!key) throw new Error(`[expo-font-families] Family "${family.family}" has no usable characters for a name`);
    if (seen.has(key))
      throw new Error(`[expo-font-families] Families "${seen.get(key)}" and "${family.family}" would both be Fonts.${key}`);
    seen.set(key, family.family);

    const faceKeys = family.faces.map(faceKey);
    const faces = family.faces.map((f, n) => {
      const style = [`fontFamily: ${JSON.stringify(family.family)}`, `fontWeight: "${f.weight}"`];
      if (f.style === "italic") style.push(`fontStyle: "italic"`);
      return `    ${faceKeys[n]}: { ${style.join(", ")} },`;
    });
    // Shown on hover: the family itself isn't a style, so point at a face.
    const example = faceKeys.includes("regular") ? "regular" : faceKeys[0];
    const doc = `  /** ${family.family.replace(/\*\//g, "")}. Use a face, e.g. \`Fonts.${key}.${example}\`. */`;
    return `${doc}\n  ${key}: {\n${faces.join("\n")}\n  },`;
  });

  const lines = [
    `${HEADER} Don't edit it: it's rewritten whenever your fonts change.`,
    `// To use it from another folder, re-export it there: export { Fonts } from "<path to this file>";`,
    "",
    `export const Fonts = {\n${families.join("\n")}\n}${typescript ? " as const" : ""};`,
  ];
  if (typescript) {
    const names = plan.families.map((f) => JSON.stringify(f.family)).join(" | ");
    lines.push("", "/** Every bundled font family name. */", `export type FontFamily = ${names};`);
  }
  return lines.join("\n") + "\n";
}

/**
 * Writes the `Fonts` module to fonts.ts (fonts.js without a tsconfig.json) in the project root.
 * Skips the write when nothing changed, so Metro doesn't reload, and never replaces a file that
 * expo-font-families didn't generate.
 */
function writeFontsModule(plan, projectRoot) {
  const typescript = fs.existsSync(path.join(projectRoot, "tsconfig.json"));
  const file = path.join(projectRoot, typescript ? "fonts.ts" : "fonts.js");
  const source = fontsModule(plan, { typescript });

  let existing = null;
  try {
    existing = fs.readFileSync(file, "utf8");
  } catch {}
  if (existing === source) return;
  if (existing !== null && !existing.startsWith(HEADER)) {
    warnOnce(
      `[expo-font-families] ${path.basename(file)} already exists and wasn't generated by expo-font-families, so the Fonts ` +
        `styles weren't written. Rename or remove your ${path.basename(file)} to get them.`
    );
    return;
  }
  fs.writeFileSync(file, source);
}

module.exports = { fontsModule, writeFontsModule, familyKey, faceKey };
